name: "Segment analyzer"
description: "Analyzer your sport activity segments!"
version: "1.0.0"
slug: "segment_analyzer"
webui: "[PROTO:ssl]://[HOST]:[PORT:5000]"
arch:
  - amd64
init: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Segment analyzer web interface
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str